-- Criação da tabela CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
    ID_CLIENT BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME_CLIENT VARCHAR(255) NOT NULL,
    CPF_CLIENT VARCHAR(11) NOT NULL UNIQUE,
    EMAIL_CLIENT VARCHAR(255) NOT NULL
);

-- Criação da tabela PRODUCT
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID_PRODUCT BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME_PRODUCT VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CATEGORY ENUM('LUNCH', 'ACCOMPANIMENT', 'DRINK', 'DESSERT') NOT NULL
);

-- Criação da tabela DEMAND
CREATE TABLE IF NOT EXISTS DEMAND (
    DEMAND_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT BIGINT NOT NULL,
    DEMAND_STATUS ENUM('CREATED', 'CONFIRMED', 'DELIVERED', 'CANCELLED') NOT NULL,
    PAYMENT_STATUS ENUM('PENDING', 'PAID', 'FAILED') DEFAULT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT) ON DELETE CASCADE
);

-- Tabela intermediária para relacionamento muitos-para-muitos entre DEMAND e PRODUCT
CREATE TABLE IF NOT EXISTS TB_DEMAND_PRODUCTS (
    DEMAND_NUMBER BIGINT NOT NULL,
    ID_PRODUCT BIGINT NOT NULL,
    PRIMARY KEY (DEMAND_NUMBER, ID_PRODUCT),
    FOREIGN KEY (DEMAND_NUMBER) REFERENCES DEMAND(DEMAND_NUMBER) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT) ON DELETE CASCADE
);

-- Configurar os valores iniciais de AUTO_INCREMENT
ALTER TABLE CLIENT AUTO_INCREMENT = 3;
ALTER TABLE PRODUCT AUTO_INCREMENT = 5;